jobs:
  include:
    - branch: master
      if: |
        NOT tag IS present
      env:
      - IMAGE="eisengrind/altv-voice-server"
      services:
      - docker
      before_script:
      - sudo apt-get install jq wget
      - chmod +x ./scripts/push.sh
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - |
        for BRANCH in dev stable rc release
        do
          ./scripts/push.sh $IMAGE $BRANCH $(wget --no-cache -qO- http://cdn.altv.mp/voice-server/${BRANCH}/x64_linux/update-info.json | jq '.latestBuildNumber')
      - docker logout
    - branch: master
      if: |
        tag IS present &&
        tag =~ /^(stable|release|rc|dev)-[0-9]+$/
      services:
      - docker
      before_script:
      - chmod +x ./scripts/push.sh
      env:
      - IMAGE="eisengrind/altv-voice-server"
      script:
      - travisTag=$TRAVIS_TAG
      - splitTag=(${travisTag//-/ })
      - BRANCH=${splitTag[0]}
      - BUILD=${splitTag[1]}

      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - ./scripts/push.sh $IMAGE $BRANCH $BUILD

      - docker logout
