name: DefaultCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: []

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  default-build:
    if: ${{!startsWith(github.ref, 'refs/tags/')}}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      IMAGE: eisengrind/altv-voice-server

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      name: checkout
    - name: install deps
      run: sudo apt-get update && sudo apt-get install -y jq wget
    - name: build & push voice server images
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

        # stable does not exist yet
        for BRANCH in dev rc release
        do
          BUILD=$(wget --no-cache -qO- http://cdn.altv.mp/voice-server/${BRANCH}/x64_linux/update-info.json | jq '.latestBuildNumber')

          docker build . --build-arg BRANCH=$BRANCH -t $IMAGE:$BUILD
          docker tag $IMAGE:$BUILD $IMAGE:$BRANCH
  
          docker push $IMAGE:$BUILD
          docker push $IMAGE:$BRANCH
        done

        docker logout
